<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ul data-split-icon="info" data-split-theme="a" data-role="listview" data-inset="true" >
    <?php foreach ($_productCollection as $_product): ?>
    <li>            
            <a href="<?php echo $_product->getProductUrl() ?>" data-ajax="false">
            <?php // Product Image ?>
            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            <?php // Product description ?>    
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></h2>
                    <?php echo $this->getPriceHtml($_product, true) ?>
            </a>
<!--            <a href="--><?php //echo $_product->getProductUrl() ?><!--" data-ajax="false">--><?php //echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?><!--</a>-->
        </li>
    <?php endforeach; ?>
    </ul>
    

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
            <ul data-split-icon="info" data-split-theme="a" data-role="listview" data-inset="true" >
            <?php foreach ($_productCollection as $_product): ?>
            <li>
                    <a href="<?php echo $_product->getProductUrl() ?>" data-ajax="false">
                    <?php // Product Image ?>
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    <?php // Product description ?>
                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <h2 class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></h2>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                    </a>
        <!--            <a href="--><?php //echo $_product->getProductUrl() ?><!--" data-ajax="false">--><?php //echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?><!--</a>-->
                </li>
            <?php endforeach; ?>
            </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
