<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body home="index.php" class="mage-iphone" onload="setTimeout(scrollTo, 0, 0, 1)">
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('breadcrumbs') ?>
    <div data-role="content">
        <?php echo $this->getChildhtml('slider') ?>

        <?php echo $this->getChildHtml('content') ?>

    </div>

    <?php echo $this->getChildHtml('footer') ?>

<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
