<!DOCTYPE html> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-popup <?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
<?php echo $this->getChildHtml('after_body_start') ?>
<div data-role="page" data-theme="b" id="one">
    <?php echo $this->getChildHtml('content') ?>    
    <?php echo $this->getChildHtml('before_body_end') ?>
</div>
    <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
