<div class="page-title">
    <h1><?php echo $this->__('Retrieve your password here') ?></h1>
</div>
<div class="forgot-password" data-role="fieldcontain">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
        <label for="email_address" class="required"><?php echo $this->__('Email Address') ?></label>
        <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
        <div class="buttons-set">
            <a data-role="button" data-icon="arrow-l" href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><?php echo $this->__('Back to Login') ?></a>
            <button type="submit" data-theme="b" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button>
        </div>
    </form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
