<title>
    <?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?>
</title>
<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0'/> 


<?php echo $this->getChildHtml() ?>
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" />
<script src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
<script src="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js"></script>

<?php echo $this->getCssJsHtml() ?>

<script type="text/javascript">
//<![CDATA[
     var $j = jQuery.noConflict();
//]]>
</script>
    