<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
    <ul class="products-grid" id="products-grid"  data-role="listview" data-inset="true">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <li>
                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" />
                <h3 class="product-name"><?php echo $this->htmlEscape($_link->getName()) ?></h3>
                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
<!--                --><?php //echo $this->getReviewsSummaryHtml($_link) ?>
                </a>
                
            </li>
            <?php else: ?>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endfor; ?>
    </ul>
    <script type="text/javascript">decorateList('products-grid')</script>
</div>
<?php endif ?>
